<a href="https://colab.research.google.com/github/madhureddy7716/TNS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Array Creation


In [1]:
import numpy as np

arr1 = np.array([10,20,30,40,50])
print(arr1)

arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)

zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((4,4))
print(ones)

identity = np.eye(5)
print(identity)

arange_arr = np.arange(1,21)
print(arange_arr)

linspace_arr = np.linspace(0,100,10)
print(linspace_arr)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


2. Array Properties


In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Datatype:", arr.dtype)

float_arr = arr.astype(float)
print(float_arr)

Shape: (2, 3)
Dimensions: 2
Size: 6
Datatype: int64
[[1. 2. 3.]
 [4. 5. 6.]]


3. Reshape and Transpose

In [3]:
arr = np.arange(1,13)

print(arr)

print(arr.reshape(3,4))
print(arr.reshape(2,6))
print(arr.reshape(4,3))

matrix = arr.reshape(3,4)
print(matrix.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


4. Mathematical Operations


In [4]:
arr = np.array([10,20,30,40,50])

print(arr + 5)
print(arr - 10)
print(arr * 2)
print(arr / 5)

print(arr ** 2)
print(arr ** 3)

[15 25 35 45 55]
[ 0 10 20 30 40]
[ 20  40  60  80 100]
[ 2.  4.  6.  8. 10.]
[ 100  400  900 1600 2500]
[  1000   8000  27000  64000 125000]


5. Aggregate Functions

In [5]:
arr = np.array([12,25,18,40,50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std:", np.std(arr))
print("Variance:", np.var(arr))

print("Min:", np.min(arr))
print("Max:", np.max(arr))

Sum: 145
Mean: 29.0
Median: 25.0
Std: 14.057026712644463
Variance: 197.6
Min: 12
Max: 50


6. Indexing and Slicing

In [6]:
arr = np.array([10,20,30,40,50,60,70])

print(arr[0])
print(arr[-1])

print(arr[:3])

print(arr[2:6])

print(arr[::2])

10
70
[10 20 30]
[30 40 50 60]
[10 30 50 70]


7. Random Numbers

In [7]:
rand_arr = np.random.rand(2,3)
print(rand_arr)

rand_int = np.random.randint(1,11,(3,3))
print(rand_int)

otp = np.random.randint(100000,999999)
print("OTP:", otp)

random_numbers = np.random.rand(5)
print(random_numbers)

[[0.7773599  0.26887971 0.64709536]
 [0.1306401  0.99666078 0.83667015]]
[[2 2 3]
 [6 8 1]
 [7 8 2]]
OTP: 729120
[0.68527519 0.0653183  0.46566831 0.93312554 0.7498509 ]


8. Sorting

In [8]:
arr = np.array([9,2,7,1,5,8])

print(np.sort(arr))

print(np.sort(arr)[::-1])

print(np.argmax(arr))

print(np.argmin(arr))

[1 2 5 7 8 9]
[9 8 7 5 2 1]
0
3


9. Matrix Operations

In [9]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A + B)

print(A - B)

print(np.dot(A,B))

print(A * B)

print(A.T)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
